.PHONY: clean All

All:
	@echo "----------Building project:[ 20190404 - Release ]----------"
	@cd "20190404" && "$(MAKE)" -f  "20190404.mk"
clean:
	@echo "----------Cleaning project:[ 20190404 - Release ]----------"
	@cd "20190404" && "$(MAKE)" -f  "20190404.mk" clean
