.PHONY: clean All

All:
	@echo "----------Building project:[ 20190409_hw1 - Release ]----------"
	@cd "20190409_hw1" && "$(MAKE)" -f  "20190409_hw1.mk"
clean:
	@echo "----------Cleaning project:[ 20190409_hw1 - Release ]----------"
	@cd "20190409_hw1" && "$(MAKE)" -f  "20190409_hw1.mk" clean
